import "./globals.css";
import { Chakra_Petch as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import SessionWrapper from "@/components/SessionWrapper";
import CustomCursor from "@/components/customCursor";
import Navbar from "@/components/Navbar";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["300", "400", "500", "600", "700"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable,
          )}
        >
          <CustomCursor>{children}</CustomCursor>
        </body>
      </html>
    </SessionWrapper>
  );
}
